### ISSUE TITLE
Looks useful, is a port to Qt5 in the cards

### ISSUE THREAD

**Issue by tobimensch** [jmechnich/sysstat-applet#1]
Hi,

this applet looks really useful.

As written in the title, is there hope for a Qt5 port?

Kind Regards

**Comment by jmechnich** [comment]
Hello there,

check out the latest commits to appletlib and sysstat-applet, I have modified the code to use PyQt5.
Thanks for reminding me to do this. :)

Please let me know if you run into any further issues.

Best,
Jörg

**Comment by tobimensch** [comment]
Thank you! That's one of the most awesome responses I've ever gotten.

**Comment by jmechnich** [comment]
> Thank you! That's one of the most awesome responses I've ever gotten.

You're welcome...the work mostly consisted of replacing 4s with 5s... ;)

I am going to close this issue. In case you are running into any crashes, please open a new one.
