### ISSUE TITLE
Misplaced sysstat overlay when systray on the right edge of second screen

### ISSUE THREAD

**Issue by tobimensch** [jmechnich/sysstat-applet#17]
My configuration is as follows:

I have a two monitor setup.

The panel is vertical and on the right side, so on the second/right monitor.

Now when clicking on the applet, the overlay appears on the first/left monitor's right edge,
instead of the second monitor's right edge where it should appear.

**Comment by jmechnich** [comment]
With the addition of the new option I have mentioned in #5, this should hopefully be fixed too (actually I have only managed to put tint2 on top, left or bottom of the screen, so it would be great if you could test this in your setup).

**Comment by jmechnich** [comment]
Closed due to inactivity, re-open if required.
